[package]
name = "cli"
version = "0.1.0"
authors = ["Markus Mayer"]
edition = "2021"
repository = "https://github.com/sunsided/graph-based-image-segmentation"
license = "MIT"
categories = ["command-line-utilities"]
publish = false

[dependencies]
opencv = "0.82.0"
graph-based-image-segmentation = { path = "../lib", version = "*" }

[profile.dev.package.opencv]
opt-level = 3
